/**
 * Analyze issues generated by the scanner to identify noise vs value
 */

import { analyzeUrlWithRules } from './scanWithRules.js';

const result = await analyzeUrlWithRules('https://github.com', { 
  maxChunkTokens: 1200,
  enableChunking: false,
  enableExtractability: false,
  enableHallucinationDetection: false,
  enableLLM: false, // Disable LLM features to focus on rules
});

console.log('╔════════════════════════════════════════════════════════════════╗');
console.log('║              Issue Analysis - Noise vs Value                   ║');
console.log('╚════════════════════════════════════════════════════════════════╝\n');

console.log(`Total Issues: ${result.issues.length}\n`);

// Group by category
const byCategory = new Map<string, typeof result.issues>();
for (const issue of result.issues) {
  if (!byCategory.has(issue.category)) {
    byCategory.set(issue.category, []);
  }
  byCategory.get(issue.category)!.push(issue);
}

console.log('Issues by Category:');
for (const [category, issues] of byCategory.entries()) {
  console.log(`\n${category}: ${issues.length} issues`);
  
  // Show first 3 examples
  issues.slice(0, 3).forEach((issue, i) => {
    console.log(`  ${i + 1}. [${issue.severity}] ${issue.title}`);
    console.log(`     ID: ${issue.id}`);
    console.log(`     Impact: ${issue.impactScore}`);
    console.log(`     Description: ${issue.description.slice(0, 100)}...`);
  });
  
  if (issues.length > 3) {
    console.log(`  ... and ${issues.length - 3} more`);
  }
}

// Analyze issue quality
console.log('\n\n╔════════════════════════════════════════════════════════════════╗');
console.log('║                    Quality Analysis                            ║');
console.log('╚════════════════════════════════════════════════════════════════╝\n');

// High impact issues (likely valuable)
const highImpact = result.issues.filter(i => i.impactScore >= 15);
console.log(`High Impact (≥15): ${highImpact.length} issues`);
highImpact.forEach(issue => {
  console.log(`  • [${issue.category}] ${issue.title} (impact: ${issue.impactScore})`);
});

// Low impact issues (likely noise)
console.log(`\nLow Impact (<5): ${result.issues.filter(i => i.impactScore < 5).length} issues`);

// Generic titles (potential noise)
const genericWords = ['missing', 'no', 'lacks', 'should', 'potential'];
const genericIssues = result.issues.filter(i => 
  genericWords.some(word => i.title.toLowerCase().includes(word))
);
console.log(`\nGeneric Titles: ${genericIssues.length} issues`);

// Issues with low confidence
const lowConfidence = result.issues.filter(i => i.confidence && i.confidence < 0.6);
console.log(`\nLow Confidence (<60%): ${lowConfidence.length} issues`);

console.log('\n\n╔════════════════════════════════════════════════════════════════╗');
console.log('║                  Recommendations                               ║');
console.log('╚════════════════════════════════════════════════════════════════╝\n');

console.log('Rules to Consider Removing/Reducing:');
console.log('  • Rules generating many low-impact issues');
console.log('  • Rules with generic, unhelpful titles');
console.log('  • Rules flagging things that may not matter for AI');
console.log('  • Rules that duplicate other analysis');
console.log('\nFocus on:');
console.log('  • Issues that directly impact AI understanding');
console.log('  • Issues with clear, actionable remediation');
console.log('  • High-impact, high-confidence issues');
console.log('  • Unique insights not available elsewhere');
